### ISSUE TITLE
Is this usable on php7.4 ?

### ISSUE THREAD

**Issue by Kilbourne** [yethee/tiktoken-php#1]

**Comment by yethee** [comment]
Currently code is not compatible with PHP 7.4.

For support PHP 7.4 we need to:

* rewrite the first-class callable syntax to old-fashioned
* replace the constructor property promotion
* downgrade PHPUnit to 9.6

**Comment by stouch** [comment]
I made this one : https://github.com/stouch/tiktoken-php-7.3
